{{- if .Values.storage.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft.storage.pvcName" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - {{ .Values.storage.access }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  {{- if .Values.storage.nfs.enabled }}
  volumeName: {{ include "minecraft.storage.pvName" . }}
  {{- end }}
  storageClassName: {{ default "" .Values.storage.pvc.storageClass | quote }}
{{- end -}}
